name: Release

on:
  push:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v -o heph .

      - name: Test
        run: "./heph test"

      - name: ReTest
        run: "./heph test"

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Pre-Build
        run: go build -v -o heph .

      - name: Self Build
        run: |
          mkdir -p dist
          ./heph cp_builds $(pwd)/dist
          ls ./dist

      - name: Upload assets
        uses: actions/upload-artifact@v2
        with:
          name: heph
          path: dist/*

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Copy to bucket
        run: |
          VERSION=${GITHUB_SHA::8}
          NOCACHE="Cache-Control: no-cache, no-store"
          
          echo $VERSION

          echo $VERSION > ./latest_version

          gsutil -h "${NOCACHE}" rsync -r './dist' gs://heph-build/${VERSION}
          gsutil -h "${NOCACHE}" cp './install.sh' gs://heph-build/install.sh
          gsutil -h "${NOCACHE}" cp './latest_version' gs://heph-build/latest_version
