name: Release

on:
  push:
    branches:
      - '*'
    paths:
      - '**'
      - '!website/**'

env:
  NOCACHE: "Cache-Control: no-cache, no-store"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "0"
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Build
        run: go build -v -o heph .

      - name: Cache .heph
        uses: actions/cache@v3
        with:
          path: .heph/cache
          key: dot-heph-test-${{ github.run_id }}
          restore-keys: |
            dot-heph-build-

      - name: Go Tests
        run: "./heph run //:go_test"

      - name: Light E2E Test
        run: "./heph run //:light_e2e_test"

      - name: Light E2E ReTest
        run: "./heph run //:light_e2e_test"

      - name: E2E Test
        run: "./heph run //:e2e_test"

      - name: intg Test
        run: "./heph run //:intg_test"

      - name: intg ReTest
        run: "./heph run //:intg_test"

      - name: Cleanup .heph
        run: |
          rm -rf .heph/cache/test

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: "0"
      HEPH_PROFILES: "release"
    outputs:
      version: ${{ steps.upload.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true

      - name: Cache .heph
        uses: actions/cache@v3
        with:
          path: .heph/cache
          key: dot-heph-build-${{ github.run_id }}
          restore-keys: |
            dot-heph-build-

      - name: Pre-Build
        run: go build -v -o heph .

      - name: Self Build
        run: |
          mkdir -p dist
          ./heph r //:cp_builds $(pwd)/dist
          ls ./dist

      - name: Upload assets
        uses: actions/upload-artifact@v3
        with:
          name: heph
          path: dist/*

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Copy to bucket
        id: upload
        run: |
          VERSION=$(cat $(./heph query out //:version))          
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          echo $VERSION

          gsutil -h "${NOCACHE}" rsync -r './dist' gs://heph-build/${VERSION}
          gsutil -h "${NOCACHE}" cp './install.sh' gs://heph-build/install.sh
          gsutil -h "${NOCACHE}" cp './hephw' gs://heph-build/hephw

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ build, test ]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Copy to bucket
        run: |
          VERSION=${{needs.build.outputs.version}}
          
          echo $VERSION > ./latest_version
          
          gsutil -h "${NOCACHE}" cp './latest_version' gs://heph-build/latest_version
